name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # or macos-latest if you prefer macOS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install


    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages  # The branch to deploy to
        build_dir: ./  # Directory to deploy (root in this case)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

