name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this matches your default branch

jobs:
  deploy:
    runs-on: macos-latest # or macos-latest if you prefer macOS

    steps:
    - name: Set up Git configuration
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Ensure this points to your build output directory, or `./` for root
